# ==============================================================================
# Splunk Enterprise — transforms.conf
# Deployment Target: $SPLUNK_HOME/etc/apps/soc_detection_app/local/transforms.conf
# Purpose: Define CSV lookup definitions and regex field extractions
# ==============================================================================

[user_privilege_lookup]
filename = user_privilege_lookup.csv
case_sensitive_match = false
default_match = Standard
min_matches = 1
max_matches = 1

# Sysmon GrantedAccess Mask to String Name Extractor
[sysmon_access_mask_lookup]
filename = sysmon_access_mask.csv
case_sensitive_match = false
